### ISSUE TITLE
[FEATURE] Request to add a  Chinese(Simplified) language file.

### ISSUE THREAD

**Issue by yxc0915** [cobrex1/TownyMenu#17]
I couldn't find the Chinese option on the Crowdin platform. If possible, I would like to assist with the translation.

**Comment by cobrex1** [comment]
@yxc0915 I have now added Chinese Simplified to Crowdin. I am not sure if you wanted this one, or one of the other 3 options, which are Traditional, Traditional Honk Kong, Traditional Macau, Traditional Singapore.
Let me know if this is not the right one I have enabled for you.
Thank you for offering to help with a translation.

**Comment by yxc0915** [comment]
> 我现在已将简体中文添加到 Crowdin。我不确定您是想要这个，还是其他 3 个选项之一，即传统、传统喇叭、传统澳门、传统新加坡。如果这不是我为您启用的正确选项，请告诉我。感谢您提供翻译帮助。

就是这个！非常感谢！
