### ISSUE TITLE
Online players not showing in GUI to invite them the town[BUG]

### ISSUE THREAD

**Issue by gamercorpse** [cobrex1/TownyMenu#2]
**Describe the bug**
When opening the GUI and navigating to the "invite player menu" it shows my player character only, and not the other people online.

**To Reproduce**
1. Create a Town
2. Open menu with /townmenu
3. Select invite player menu tab
4. Can only myself, not other players

**Expected behavior**
Expected to see other online players to invite to my tone.

**Screenshots**
![2022-07-11_15 03 08](https://user-images.githubusercontent.com/93364815/178366467-50a50ed3-524d-42bc-82a4-8f75a0522354.png)

**Plugin Version:**
1.4.1

**Server Jar and Version:**
Paper 1.19.41

**Additional context**
N/A

**Comment by cobrex1** [comment]
OK, thanks, I will look to have this fixed soon

**Comment by cobrex1** [comment]
This issues is now fixed in the latest commit release, 1.4.3
