### ISSUE TITLE
[BUG] folia async problem

### ISSUE THREAD

**Issue by Potenza7** [cobrex1/TownyMenu#22]
**Describe the bug**
When you click on the menu and try to create that town, it gives an error when you type in the chat.

**To Reproduce**
add folia schedulers
**Expected behavior**
fix

**Screenshots**
https://mclo.gs/M3i5TMl

**Plugin Version:**
Lastest 1.8.8

**Server Jar and Version:**
1.21.1 Folia

**Comment by cobrex1** [comment]
Sorry for the delay, please try 1.8.9 - this should fix the issues.
