### ISSUE TITLE
[BUG] /tm Don't work

### ISSUE THREAD

**Issue by XionioXMaster** [cobrex1/TownyMenu#4]
**Describe the bug**
![image](https://user-images.githubusercontent.com/86433158/184529359-d5a40cdf-ba2f-4874-b937-fa7b3f062dbb.png)

**To Reproduce**
1. /tm and see log

**Plugin Version:**
1.15.1

**Server Jar and Version:**
![image](https://user-images.githubusercontent.com/86433158/184529377-d52b3572-fbd4-47e6-bb79-23cef5692c8d.png)

Log: https://mcpaste.com/8ff5c9cc9f25ba32b32ae209e7ffdf7e

**Comment by XionioXMaster** [comment]
The error has disappeared after 6 inputs

[But it is impossible to create a city](https://www.youtube.com/watch?v=u0ycbhTBBd8)

**Comment by cobrex1** [comment]
Hi XionioXMaster,

I am aware that the the new town prompt is not working as it should. If you just type /confirm after typing in the town name it will work. 

I am having an issue getting the towny prompts to reply outside of the Pompt conversation I am running.

Hopefully I will find a fix.

**Comment by cobrex1** [comment]
This issue has now been fixed with 1.5.2 update and commit cb0bdd1

**Comment by XionioXMaster** [comment]
not fixed
