### ISSUE TITLE
[BUG] /tm Don't create town

### ISSUE THREAD

**Issue by XionioXMaster** [cobrex1/TownyMenu#5]
**Describe the bug**
I still can't create a town

**To Reproduce**
![image](https://user-images.githubusercontent.com/86433158/185362446-7b28febe-aa29-4c88-a51c-fbb87e4ce634.png)
![image](https://user-images.githubusercontent.com/86433158/185362496-7b1c98b1-67a8-43e2-a289-4acdaa0ad834.png)
![image](https://user-images.githubusercontent.com/86433158/185362509-e0c917d7-63bf-4d81-bd90-9802e6087bb5.png)

**Expected behavior**

**Screenshots**

**Plugin Version:**
1.5.3

**Server Jar and Version:**
E.g Patina1.19.2

**Additional context**

**Comment by cobrex1** [comment]
no response to request for information, closing.
