### ISSUE TITLE
[FEATURE] Possibility to use CustomModelData

### ISSUE THREAD

**Issue by ImLeonardoo** [cobrex1/TownyMenu#6]
**Is your feature request related to a problem? Please describe.**
I can't set custom textures for items in the menu.
**Describe the solution you'd like**
Set custom texture using CustomModelData.
**Describe alternatives you've considered**
Don't use textures.
**Additional context**

Example of configuration:

` 
items:

    nationToggle: paper

       CustomModelData: 100
`

**Comment by cobrex1** [comment]
This might be something I will look to add

**Comment by cobrex1** [comment]
@ImLeonardoo This will be added in the next release - hopefully later today, or tomorrow :)

Took me a little longer than planned but almost there.

**Comment by cobrex1** [comment]
Add to the latest release #b391c3d
Closing
